import type { Flow } from '@/lib/flow';

/** Diagram 1 — the whole path, and the one loop in it. */
export const overviewFlow: Flow = {
  id: 'overview',
  title: 'A ticket from request to shipped code',
  subtitle:
    'Four phases. Each one produces a document a human signs off on before the next one starts.',
  footnote:
    'The loop runs when building surfaces something that needs rethinking, when the scope changes, or when the work was split into several iterations on purpose. Each iteration gets its own plan, and the earlier ones are kept.',
  columns: 3,
  nodeWidth: 268,
  gapX: 52,
  gapY: 112,
  nodes: [
    {
      id: 'setup',
      kicker: 'Setup',
      title: 'Set up the workspace',
      body: 'A Linear issue URL goes in. A git worktree, a branch and a state file come out.',
      role: 'grey',
      col: 0,
      row: 0,
      href: '#setting-up-the-workspace',
    },
    {
      id: 'p1',
      title: 'Context Phase',
      body: "Capture the customer problem in the customer's own words, before touching any code.",
      role: 'amber',
      col: 1,
      row: 0,
      href: '#context',
    },
    {
      id: 'p2',
      title: 'Codebase Research Phase',
      body: 'Document how the relevant part of the system works today. Describe, never redesign.',
      role: 'purple',
      col: 2,
      row: 0,
      href: '#codebase-research',
    },
    {
      id: 'p9',
      title: 'Implementation Plan Phase',
      body: 'Write the whole change down and agree on it — still not one line of code.',
      role: 'blue',
      col: 2,
      row: 1,
      href: '#implementation-plan',
    },
    {
      id: 'p10',
      title: 'Implementation Phase',
      body: 'Build it in order, verifying each step before starting the next one.',
      role: 'green',
      col: 1,
      row: 1,
      href: '#implementation',
    },
    {
      id: 'ship',
      kicker: 'Ship',
      title: 'Review & Ship',
      body: 'Pull request, /code-review, human review in Slack, merge, Linear ticket closed.',
      role: 'grey',
      col: 0,
      row: 1,
      href: '#review-and-ship',
    },
  ],
  edges: [
    { from: 'setup', to: 'p1' },
    { from: 'p1', to: 'p2' },
    { from: 'p2', to: 'p9' },
    { from: 'p9', to: 'p10' },
    { from: 'p10', to: 'ship' },
    {
      from: 'p10',
      to: 'p9',
      kind: 'loop',
      lane: 'below',
      label: 'Needs planning again, a new iteration',
    },
  ],
};

/** Diagram 2 — the automated setup that happens before any thinking starts. */
export const setupFlow: Flow = {
  id: 'setup',
  title: 'Before the Context Phase: setting up the workspace',
  subtitle: 'One command. About a minute, no decisions to make.',
  columns: 6,
  nodeWidth: 166,
  gapX: 28,
  nodes: [
    {
      id: 's1',
      title: 'Linear issue URL',
      body: 'ks-start-ticket, run from the main checkout.',
      role: 'grey',
      col: 0,
      row: 0,
    },
    {
      id: 's2',
      title: 'Issue read from Linear',
      body: 'Ticket details, via the in-house linear CLI.',
      role: 'blue',
      col: 1,
      row: 0,
    },
    {
      id: 's3',
      title: 'state.yaml written',
      body: 'The phase list, statuses and timestamps. Schema-enforced.',
      role: 'blue',
      col: 2,
      row: 0,
    },
    {
      id: 's4',
      title: 'git worktree created',
      body: 'New branch, sibling directory. .env files and CLAUDE.local.md copied in.',
      role: 'blue',
      col: 3,
      row: 0,
    },
    {
      id: 's4b',
      title: 'Packages built',
      body: 'pnpm install, workspace packages built in dependency order.',
      role: 'blue',
      col: 4,
      row: 0,
    },
    {
      id: 's5',
      title: 'Session launched',
      body: 'claude-ks starts Claude Code in the worktree; its first message loads /ks:project-manager and starts the workflow.',
      role: 'blue',
      col: 5,
      row: 0,
    },
    {
      id: 'out',
      kicker: 'Outcome',
      title: 'Ready for the Context Phase',
      body: 'An isolated branch and tree, ready to build, and one file that says which phase we are in.',
      role: 'green',
      col: 1,
      row: 1,
      colSpan: 4,
      variant: 'panel',
    },
  ],
  edges: [
    { from: 's1', to: 's2' },
    { from: 's2', to: 's3' },
    { from: 's3', to: 's4' },
    { from: 's4', to: 's4b' },
    { from: 's4b', to: 's5' },
    { from: 's5', to: 'out' },
  ],
};

/** Diagram 3 — the wrapper every phase runs inside. */
export const rhythmFlow: Flow = {
  id: 'rhythm',
  title: 'The rhythm every phase follows',
  subtitle:
    'The four phases differ in what they produce. How they run is identical — so you only have to learn it once.',
  footnote:
    'A phase can also be skipped outright, or revisited later. When an earlier phase is revisited, the phases that were based on it are flagged so they get redone.',
  columns: 4,
  gapY: 136,
  nodes: [
    {
      id: 'ask',
      title: 'Ask first',
      body: 'Run this phase, or skip it? Nothing starts without a yes.',
      role: 'amber',
      col: 0,
      row: 0,
    },
    {
      id: 'start',
      title: 'Mark it in progress',
      body: 'status: IN_PROGRESS, plus a start timestamp.',
      role: 'grey',
      col: 1,
      row: 0,
    },
    {
      id: 'work',
      title: 'Do the work',
      body: 'The phase skill runs and writes its document.',
      role: 'green',
      col: 2,
      row: 0,
    },
    {
      id: 'read',
      title: 'You read the output',
      body: 'Sign it off, or send it back with changes.',
      role: 'amber',
      col: 3,
      row: 0,
    },
    {
      id: 'done',
      title: 'Mark it complete',
      body: 'COMPLETED, or SKIPPED, with an end timestamp.',
      role: 'grey',
      col: 2,
      row: 1,
    },
    {
      id: 'handoff',
      title: 'Write a handoff note',
      body: '/ks:create_handoff records what was decided.',
      role: 'blue',
      col: 1,
      row: 1,
    },
    {
      id: 'next',
      title: 'Move to the next phase',
      body: 'A fresh session, carrying the handoff with it.',
      role: 'blue',
      col: 0,
      row: 1,
    },
  ],
  edges: [
    { from: 'ask', to: 'start' },
    { from: 'start', to: 'work' },
    { from: 'work', to: 'read' },
    { from: 'read', to: 'done', label: 'signed off' },
    {
      from: 'ask',
      to: 'done',
      kind: 'optional',
      lane: 'below',
      laneOffset: -38,
      label: 'skipped — the phase never runs',
    },
    { from: 'done', to: 'handoff' },
    { from: 'handoff', to: 'next' },
    {
      from: 'read',
      to: 'work',
      kind: 'loop',
      lane: 'above',
      label: 'changes requested — run it again',
    },
  ],
};

/** Diagram 4 — the five questions of the Context phase. */
export const contextFlow: Flow = {
  id: 'context',
  title: 'Context Phase',
  subtitle:
    'Five questions, asked one at a time. The answers become the document everything later is built on.',
  footnote:
    'This phase is deliberately slow and human. Everything built later is only as good as the problem captured here.',
  columns: 5,
  nodeWidth: 178,
  gapX: 34,
  gapY: 96,
  nodes: [
    {
      id: 'q1',
      kicker: 'Q1',
      title: 'The problem',
      body: 'What is going wrong for the customer today, in their own words?',
      role: 'amber',
      col: 0,
      row: 0,
    },
    {
      id: 'q2',
      kicker: 'Q2',
      title: "Today's workaround",
      body: 'How do they cope with it now — spreadsheets, manual checks, simply living with it?',
      role: 'amber',
      col: 1,
      row: 0,
    },
    {
      id: 'q3',
      kicker: 'Q3',
      title: 'The idea',
      body: 'What are we thinking of building, in one or two sentences?',
      role: 'amber',
      col: 2,
      row: 0,
    },
    {
      id: 'q4',
      kicker: 'Q4',
      title: 'The assumptions',
      body: 'What are we taking on trust that could later turn out to be false?',
      role: 'amber',
      col: 3,
      row: 0,
    },
    {
      id: 'q5',
      kicker: 'Q5',
      title: 'The summary',
      body: 'The whole thing said back in one short paragraph.',
      role: 'amber',
      col: 4,
      row: 0,
    },
    {
      id: 'readback',
      title: 'The answers are read back to you',
      role: 'blue',
      col: 4,
      row: 1,
    },
    {
      id: 'check',
      kicker: 'Check',
      title: 'Does this match reality?',
      role: 'amber',
      col: 3,
      row: 1,
    },
    {
      id: 'saved',
      title: 'Context document saved',
      role: 'green',
      col: 2,
      row: 1,
    },
  ],
  edges: [
    { from: 'q1', to: 'q2' },
    { from: 'q2', to: 'q3' },
    { from: 'q3', to: 'q4' },
    { from: 'q4', to: 'q5' },
    { from: 'q5', to: 'readback' },
    { from: 'readback', to: 'check' },
    { from: 'check', to: 'saved', label: 'yes' },
    {
      from: 'check',
      to: 'q1',
      kind: 'loop',
      lane: 'above',
      label: 'not quite — answer again',
    },
  ],
};

/** Diagram 5 — the parallel work of the Codebase Research phase. */
export const researchFlow: Flow = {
  id: 'research',
  title: 'Codebase Research Phase',
  subtitle: 'Understand how the system works today, before anyone decides how to change it.',
  columns: 4,
  gapY: 44,
  nodes: [
    {
      id: 'r1',
      kicker: 'Step 1',
      title: 'Agree what we need to understand',
      role: 'amber',
      col: 0,
      row: 1,
    },
    {
      id: 'r2',
      kicker: 'Step 2',
      title: 'Split it into smaller questions',
      role: 'blue',
      col: 1,
      row: 1,
    },
    {
      id: 'r3a',
      kicker: 'Step 3a',
      title: 'Where does it live?',
      body: 'codebase-locator — where things live.',
      role: 'purple',
      col: 2,
      row: 0,
    },
    {
      id: 'r3b',
      kicker: 'Step 3b',
      title: 'How does it work today?',
      body: 'codebase-analyzer — how they work, without critique.',
      role: 'purple',
      col: 2,
      row: 1,
    },
    {
      id: 'r3c',
      kicker: 'Step 3c',
      title: 'Has this been solved before?',
      body: 'codebase-pattern-finder — patterns worth copying.',
      role: 'purple',
      col: 2,
      row: 2,
    },
    {
      id: 'r4',
      kicker: 'Step 4',
      title: 'Merged into one research document',
      body: 'codebase-research.md, with file and line references. Re-running updates it.',
      role: 'green',
      col: 3,
      row: 1,
    },
  ],
  groups: [
    {
      id: 'parallel',
      label: 'Subagents in parallel, via Serena MCP',
      nodes: ['r3a', 'r3b', 'r3c'],
    },
  ],
  edges: [
    { from: 'r1', to: 'r2' },
    { from: 'r2', to: 'r3a' },
    { from: 'r2', to: 'r3b' },
    { from: 'r2', to: 'r3c' },
    { from: 'r3a', to: 'r4' },
    { from: 'r3b', to: 'r4' },
    { from: 'r3c', to: 'r4' },
  ],
};

/** Diagram 6 — writing and agreeing the plan. */
export const planFlow: Flow = {
  id: 'plan',
  title: 'Implementation Plan Phase',
  subtitle: 'Decide everything before writing anything. No code is produced in this phase.',
  footnote:
    'Nothing is built in this phase. The plan itself is the deliverable, and it is meant to be argued with.',
  columns: 4,
  gapY: 90,
  nodes: [
    {
      id: 'pl1',
      kicker: 'Step 1',
      title: 'Read everything',
      body: 'The ticket, the context document and the research document.',
      role: 'blue',
      col: 0,
      row: 0,
    },
    {
      id: 'pl2',
      kicker: 'Step 2',
      title: 'Close the gaps',
      body: 'Dig into whatever is still unclear, and put the open questions back to you.',
      role: 'blue',
      col: 1,
      row: 0,
    },
    {
      id: 'pl3',
      kicker: 'Step 3',
      title: 'Agree the shape',
      body: 'A short outline of the plan, checked with you before any detail is written.',
      role: 'amber',
      col: 2,
      row: 0,
    },
    {
      id: 'pl4',
      kicker: 'Step 4',
      title: 'Write the plan in full',
      body: 'Every change, in the order it has to happen.',
      role: 'blue',
      col: 3,
      row: 0,
    },
    {
      id: 'contents',
      kicker: 'What the plan contains',
      title:
        'Every change, grouped into ordered steps · how each step is checked automatically · what a human must click to confirm it works · the tests to be written · what we are deliberately not doing · the questions still open',
      role: 'grey',
      col: 0,
      row: 1,
      colSpan: 4,
      variant: 'panel',
    },
    {
      id: 'approve',
      kicker: 'Check',
      title: 'You approve the plan',
      role: 'amber',
      col: 1,
      row: 2,
      colSpan: 2,
      variant: 'panel',
    },
  ],
  edges: [
    { from: 'pl1', to: 'pl2' },
    { from: 'pl2', to: 'pl3' },
    { from: 'pl3', to: 'pl4' },
    { from: 'pl4', to: 'contents' },
    { from: 'contents', to: 'approve' },
    {
      from: 'approve',
      to: 'pl4',
      kind: 'loop',
      lane: 'right',
      label: 'changes needed — rewrite it',
    },
  ],
};

/** Diagram 7 — the repeating build loop of the Implementation phase. */
export const buildFlow: Flow = {
  id: 'build',
  title: 'Implementation Phase',
  subtitle:
    'Build the plan in the order it was written, checking each step before starting the next.',
  columns: 4,
  gapY: 132,
  nodes: [
    {
      id: 'b1',
      kicker: 'Step 1',
      title: 'Read the plan again',
      body: 'Together with the context and research documents.',
      role: 'blue',
      col: 0,
      row: 0,
    },
    {
      id: 'b2',
      kicker: 'Step 2',
      title: 'Ask anything still unclear',
      body: 'Better asked now than discovered half-built.',
      role: 'amber',
      col: 1,
      row: 0,
    },
    {
      id: 'b3',
      kicker: 'Step 3',
      title: 'Turn the plan into a task list',
      body: 'Every checkbox becomes a task, before any code is touched.',
      role: 'blue',
      col: 2,
      row: 0,
    },
    {
      id: 'group',
      title: 'Group the work',
      body: 'Different files share a group; the same file splits them.',
      role: 'blue',
      col: 0,
      row: 1,
    },
    {
      id: 'parallel',
      title: 'Build in parallel',
      body: 'One subagent per task.',
      role: 'blue',
      col: 1,
      row: 1,
    },
    {
      id: 'collect',
      title: 'Collect the results',
      body: 'The orchestrator reviews anything cross-cutting.',
      role: 'blue',
      col: 2,
      row: 1,
    },
    {
      id: 'verify',
      title: 'Verify before moving on',
      body: 'Types, lint and tests must pass.',
      role: 'green',
      col: 3,
      row: 1,
    },
    {
      id: 'replan',
      title: 'Another iteration',
      body: 'Plan finished, more work remains. A new plan, then this phase again.',
      role: 'amber',
      col: 0,
      row: 2,
      colSpan: 2,
    },
    {
      id: 'ready',
      title: 'Ready for review',
      body: 'Every step built, verified and committed in order.',
      role: 'green',
      col: 2,
      row: 2,
      colSpan: 2,
    },
  ],
  groups: [
    {
      id: 'repeat',
      label: 'Repeated for every step of the plan',
      nodes: ['group', 'parallel', 'collect', 'verify'],
    },
  ],
  edges: [
    { from: 'b1', to: 'b2' },
    { from: 'b2', to: 'b3' },
    { from: 'b3', to: 'group' },
    { from: 'group', to: 'parallel' },
    { from: 'parallel', to: 'collect' },
    { from: 'collect', to: 'verify' },
    {
      from: 'verify',
      to: 'group',
      kind: 'success',
      lane: 'below',
      // Lifted clear of the lane the exits out of the loop travel in.
      laneOffset: -26,
      label: 'on to the next step of the plan',
    },
    { from: 'verify', to: 'replan', kind: 'loop' },
    { from: 'verify', to: 'ready', kind: 'success' },
  ],
};

/** Diagram 8 — everything after the code is written. */
export const shipFlow: Flow = {
  id: 'ship',
  title: 'After the Implementation Phase — review and ship',
  subtitle: 'The work still has to convince a machine and a human before it reaches anyone else.',
  footnote: 'Nothing reaches the shared codebase until both reviews are satisfied.',
  columns: 4,
  gapY: 112,
  nodes: [
    {
      id: 'pr',
      kicker: 'Step 1',
      title: 'Open a pull request',
      body: 'The proposed change, linked back to the original ticket.',
      role: 'blue',
      col: 0,
      row: 0,
    },
    {
      id: 'autoreview',
      kicker: 'Step 2',
      title: 'Automated review',
      body: 'A reviewer reads the change and reports anything suspicious.',
      role: 'purple',
      col: 1,
      row: 0,
    },
    {
      id: 'fix',
      kicker: 'Step 3',
      title: 'Fix what it found',
      body: 'Then have it reviewed again.',
      role: 'blue',
      col: 2,
      row: 0,
    },
    {
      id: 'askreview',
      kicker: 'Step 4',
      title: 'Ask a teammate to review',
      body: 'Posted in the team chat with a link to the change.',
      role: 'amber',
      col: 3,
      row: 0,
    },
    {
      id: 'humanreview',
      kicker: 'Step 5',
      title: 'Human review',
      body: 'Questions, comments, and changes until they are happy.',
      role: 'amber',
      col: 2,
      row: 1,
    },
    {
      id: 'merge',
      kicker: 'Step 6',
      title: 'Merge',
      body: 'The change joins the main codebase and goes out with the next release.',
      role: 'green',
      col: 1,
      row: 1,
    },
    {
      id: 'closed',
      kicker: 'Step 7',
      title: 'Ticket closed',
      body: 'The ticket and the progress tracker end in the same state: done.',
      role: 'green',
      col: 0,
      row: 1,
    },
  ],
  edges: [
    { from: 'pr', to: 'autoreview' },
    { from: 'autoreview', to: 'fix' },
    { from: 'fix', to: 'askreview' },
    { from: 'askreview', to: 'humanreview' },
    { from: 'humanreview', to: 'merge' },
    { from: 'merge', to: 'closed' },
    {
      from: 'fix',
      to: 'autoreview',
      kind: 'loop',
      lane: 'above',
      label: 're-review',
    },
    {
      from: 'humanreview',
      to: 'fix',
      kind: 'loop',
      lane: 'above',
      label: 'changes requested — back to Step 3',
    },
  ],
};

/** Diagram 9 — the states a phase can be in. */
export const statesFlow: Flow = {
  id: 'states',
  title: 'The states a phase moves through',
  subtitle:
    'At any moment every phase sits in exactly one of these states, recorded in the progress tracker.',
  footnote:
    'The last state is the one that matters most: when an earlier phase is revisited, every phase that was built on it is flagged automatically, so stale work cannot quietly survive.',
  columns: 4,
  nodeWidth: 224,
  gapX: 44,
  gapY: 100,
  nodes: [
    {
      id: 'notstarted',
      title: 'Not started',
      body: 'Waiting its turn.',
      role: 'grey',
      col: 0,
      row: 0,
    },
    {
      id: 'inprogress',
      title: 'In progress',
      body: 'Being worked on now.',
      role: 'blue',
      col: 1,
      row: 0,
    },
    {
      id: 'completed',
      title: 'Completed',
      body: 'Signed off by a human.',
      role: 'green',
      col: 2,
      row: 0,
    },
    {
      id: 'skipped',
      title: 'Skipped',
      body: 'Not needed for this ticket.',
      role: 'grey',
      col: 0,
      row: 1,
    },
    {
      id: 'revisiting',
      title: 'Revisiting',
      body: 'Being redone after new facts came to light.',
      role: 'amber',
      col: 2,
      row: 1,
    },
    {
      id: 'invalidated',
      title: 'Invalidated',
      body: 'An earlier phase changed, so this one must be done again.',
      role: 'red',
      col: 3,
      row: 1,
    },
  ],
  edges: [
    { from: 'notstarted', to: 'inprogress' },
    { from: 'inprogress', to: 'completed' },
    { from: 'notstarted', to: 'skipped' },
    { from: 'completed', to: 'revisiting' },
    { from: 'revisiting', to: 'inprogress', label: 'redo the phase' },
    { from: 'completed', to: 'invalidated', kind: 'loop' },
  ],
};

export const diagrams = {
  overviewFlow,
  setupFlow,
  rhythmFlow,
  contextFlow,
  researchFlow,
  planFlow,
  buildFlow,
  shipFlow,
  statesFlow,
};
